version: "3.8"
services:
  postgresdb:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_db
    networks:
      - postgres_network
  server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgresdb
networks:
  postgres_network:
